### ISSUE TITLE
Please add attribution to Renee French

### ISSUE THREAD

**Issue by ianlancetaylor** [MariaLetta/free-gophers-pack#3]
Hi, these are some beautiful images.  I'm writing here to ask if you could add an attribution to Renee French, the creator of the Go Gopher.  As discussed at https://blog.golang.org/gopher

> The gopher images are Creative Commons Attribution 3.0 licensed. That means you can play with the images but you must give credit to their creator (Renee French) wherever they are used.

Thanks!

**Comment by MariaLetta** [comment]
Hi and thanks for your interest.
I'm aware of Renee French's gopher original work, however these gophers are not based on it, and not derivatives. The "concept" and "idea" are not subjects to copyright laws. This means that if anyone wants to create his own gopher he not necessarily has to give credit to Renee French unless he is using her work.

**Comment by ianlancetaylor** [comment]
I am not a lawyer, but I agree that, as far as I know, it is not required.  I see now that my quote, which refers only to those specific images, looks too strong, and I apologize for that.

But Renee has donated a considerable amount of work to the Go project to provide gopher images.  Some of the interest in your beautiful images are surely due to her hard work.  I am suggesting that, as a matter of courtesy, it would be nice if you could add that attribution.  Thanks.

**Comment by MariaLetta** [comment]
1. I am lawyer.
2. Tbh as a professional illustrator I haven't seen "hard work" by Renee French, but I see that she is Rob Pike's wife. Also I have seen other talented illustrators in Go Community which didn't get fair recognition.
3. I hope in each of your program, or library, or piece of code you mention name of Rob Pike, because this man did really hard work. 

This issue is closed.
